runtime: nodejs20
env: standard

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
  target_throughput_utilization: 0.6

env_variables:
  VITE_SUPABASE_URL: ${VITE_SUPABASE_URL}
  VITE_SUPABASE_ANON_KEY: ${VITE_SUPABASE_ANON_KEY}
  NODE_ENV: "production"

handlers:
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto

entrypoint: node server.js
