runtime: nodejs20
env: standard

env_variables:
  VITE_SUPABASE_URL: ${VITE_SUPABASE_URL}
  VITE_SUPABASE_ANON_KEY: ${VITE_SUPABASE_ANON_KEY}

handlers:
- url: /(.*\..+)$
  static_files: dist/\1
  upload: dist/(.*\..+)$
  # catch all handler to index.html
- url: /.*
  static_files: dist/index.html
  upload: dist/index.html
